import 'package:flutter_quiz/question.dart';

import 'quiz_page.dart';

final List<Question> allQuestions = [
  Question(
    id: 1,
    question_text: "O que é esquema rígido em bancos de dados SQL?",
    options: ["O esquema dos dados não pode ser modificado após a criação do banco de dados.",
      "O esquema dos dados pode ser modificado a qualquer momento sem restrições.",
      "O esquema dos dados pode ser modificado, mas apenas por um administrador.",
      "O esquema dos dados é definido pelos usuários finais."],
    correctAnswer:0,
  ),
  Question(
    id: 2,
    question_text: "Qual das seguintes opções é verdadeira sobre bancos de dados NoSQL?",
    options: ["São projetados principalmente para dados não estruturados.",
      "São projetados principalmente para dados estruturados.", "Podem ser utilizados apenas para consultas simples.",
      "São projetados para suportar apenas baixos volumes de dados."],
    correctAnswer:1,
  ),Question(
    id: 3,
    question_text: "Qual é um exemplo de banco de dados NoSQL baseado em documentos?",
    options: ["MySQL", "PostgreSQL", "MongoDB", "SQLite"],
    correctAnswer:2,
  ),Question(
    id: 4,
    question_text: "Qual das seguintes declarações é verdadeira sobre bancos de dados NoSQL em relação a consultas complexas?",
    options: ['Bancos de dados NoSQL não são adequados para consultas complexas.',
      'Bancos de dados NoSQL têm desempenho inferior em consultas complexas.',
      'Bancos de dados NoSQL são altamente adequados para consultas complexas.',
      'Bancos de dados NoSQL possuem recursos limitados para consultas complexas.'],
    correctAnswer:2,
  ),Question(
    id: 5,
    question_text: "Qual das seguintes opções é verdadeira sobre bancos de dados SQL em relação à consistência de dados?",
    options: ['Bancos de dados SQL garantem consistência forte em relação aos dados.',
      'Bancos de dados SQL garantem consistência fraca em relação aos dados.',
      'Bancos de dados SQL fornecem melhor consistência em relação aos dados.',
      'Bancos de dados SQL não oferecem recursos de consistência.'],
    correctAnswer:2,
  ),Question(
    id: 6,
    question_text: "O que é escalabilidade vertical em bancos de dados?",
    options: ['Aumentar a capacidade de armazenamento em um único servidor.',
      'Aumentar a capacidade de processamento em um único servidor.',
      'Distribuir o armazenamento e o processamento em vários servidores.',
      'Reduzir a capacidade de armazenamento em um único servidor.'],
    correctAnswer:0,
  ),Question(
    id: 7,
    question_text: "Qual é um exemplo de banco de dados NoSQL baseado em chave-valor?",
    options: ["Cassandra", "PostgreSQL", "MongoDB", "SQLite"],
    correctAnswer:0,
  ),Question(
    id: 8,
    question_text: "Qual das seguintes opções é verdadeira sobre bancos de dados NoSQL baseados em grafos?",
    options: ['Armazenam dados em formato tabular e suportam consultas SQL.',
      'Armazenam dados em formato de árvore e garantem alta consistência.',
      'Armazenam entidades e relacionamentos e suportam linguagens de consulta de grafos.',
      'Armazenam dados em formato de documento JSON e consultas são baseadas em chaves e valores.'],
    correctAnswer:2,
  ),Question(
    id: 9,
    question_text: "Qual das seguintes opções é verdadeira sobre bancos de dados NoSQL?",
    options: ['Bancos de dados NoSQL suportam transações ACID.',
      'Bancos de dados NoSQL têm vantagem na execução de consultas complexas.',
      'Bancos de dados NoSQL são altamente escaláveis tanto vertical quanto horizontalmente.',
      'Bancos de dados NoSQL possuem esquema rígido como os bancos de dados SQL.'],
    correctAnswer:1,
  ),Question(
    id: 10,
    question_text: "Qual é um exemplo de banco de dados NoSQL baseado em colunas?",
    options: ["MySQL", "CouchDB", "Cassandra", "Redis"],
    correctAnswer:2,
  ),Question(
    id: 11,
    question_text: "Qual é um exemplo de banco de dados NoSQL baseado em documentos?",
    options: ["CouchDB","MySQL", "PostgreSQL","SQLite"],
    correctAnswer:0,
  ),Question(
    id: 12,
    question_text: "Qual das seguintes opções é verdadeira sobre bancos de dados NoSQL?",
    options: ['Bancos de dados NoSQL não suportam transações ACID.',
      'Bancos de dados NoSQL possuem esquema rígido como os bancos de dados SQL.',
      'Bancos de dados NoSQL são altamente escaláveis tanto vertical quanto horizontalmente.',
      'Bancos de dados NoSQL são projetados apenas para consultas simples.'],
    correctAnswer:0,
  ),Question(
    id: 13,
    question_text: "Qual é um exemplo de banco de dados NoSQL baseado em grafos?",
    options: ['MySQL', 'PostgreSQL', 'MongoDB', 'OrientDB'],
    correctAnswer:3,
  ),Question(
    id: 14,
    question_text: "Qual é um exemplo de banco de dados NoSQL baseado em documentos?",
    options: ['Atomicidade, Consistência, Isolamento, Durabilidade',
      'Agilidade, Conformidade, Integridade, Durabilidade',
      'Autenticidade, Credibilidade, Integridade, Desempenho',
      'Arquivamento, Compactação, Indexação, Descompressão'],
    correctAnswer:0,
  ),Question(
    id: 15,
    question_text: "Qual das seguintes opções é verdadeira sobre bancos de dados SQL?",
    options: ['Bancos de dados SQL têm esquema flexível.',
      'Bancos de dados SQL não suportam transações ACID.',
      'Bancos de dados SQL são altamente escaláveis apenas horizontalmente.',
      'Bancos de dados SQL são adequados apenas para consultas simples.'],
    correctAnswer:0,
  ),Question(
    id: 16,
    question_text: "Qual das seguintes opções é verdadeira sobre bancos de dados NoSQL em relação à escalabilidade?",
    options: ['Bancos de dados NoSQL são escaláveis apenas verticalmente.',
      'Bancos de dados NoSQL são escaláveis apenas horizontalmente.',
      'Bancos de dados NoSQL são escaláveis tanto vertical quanto horizontalmente.',
      'Bancos de dados NoSQL não são escaláveis.'],
    correctAnswer:2,
  ),Question(
    id: 17,
    question_text:"O que é consistência eventual em bancos de dados NoSQL?",
    options: ['Garante que todos os nós de um cluster de banco de dados estejam atualizados em tempo real.',
      'Permite que os dados sejam consistentes após um período de tempo, sem garantir imediatamente após a gravação.',
      'Mantém os dados consistentes em diferentes bancos de dados NoSQL.',
      'Garante a consistência em transações complexas em bancos de dados NoSQL.'],
    correctAnswer:1,
  ),Question(
    id: 18,
    question_text: "Quais são as desvantagens de usar um banco de dados NoSQL?",
    options: ['Falta de suporte a consultas complexas e falta de suporte a transações ACID.',
      'Dificuldade de escalabilidade e maior complexidade de desenvolvimento.',
      'Baixa disponibilidade e falta de flexibilidade no esquema de dados.',
      'Menor desempenho em consultas ad-hoc e falta de suporte a consultas SQL.'],
    correctAnswer:0,
  ),Question(
    id: 19,
    question_text: "Qual das seguintes opções é um exemplo de banco de dados SQL?",
    options: ['Cassandra', 'MongoDB', 'PostgreSQL', 'Redis'],
    correctAnswer:2,
  ),Question(
    id: 20,
    question_text: "Quais são os principais tipos de bancos de dados SQL?",
    options: ['Baseados em documentos, baseados em chave-valor, baseados em colunas e baseados em grafos.',
      'Baseados em tabelas, baseados em objetos, baseados em XML e baseados em JSON.',
      'Baseados em registros, baseados em conjuntos, baseados em arrays e baseados em matrizes.',
      'Baseados em arquivos, baseados em cache, baseados em pilhas e baseados em filas.'],
    correctAnswer:1,
  ),Question(
    id: 21,
    question_text: "Qual das seguintes declarações é verdadeira sobre bancos de dados SQL em relação à escalabilidade?",
    options: ['Bancos de dados SQL são escaláveis apenas verticalmente.',
      'Bancos de dados SQL são escaláveis apenas horizontalmente.',
      'Bancos de dados SQL são escaláveis tanto vertical quanto horizontalmente.',
      'Bancos de dados SQL não são escaláveis.'],
    correctAnswer:0,
  ),Question(
    id: 22,
    question_text: "Qual é um exemplo de banco de dados NoSQL baseado em documentos?",
    options: ['MySQL', 'PostgreSQL', 'CouchDB', 'SQLite'],
    correctAnswer:2,
  ),Question(
    id: 23,
    question_text: "Qual das seguintes opções é verdadeira sobre bancos de dados NoSQL?",
    options: ['Bancos de dados NoSQL suportam transações ACID.',
      'Bancos de dados NoSQL possuem esquema rígido como os bancos de dados SQL.',
      'Bancos de dados NoSQL são altamente escaláveis tanto vertical quanto horizontalmente.',
      'Bancos de dados NoSQL são projetados apenas para consultas simples.'],
    correctAnswer:0,
  ),Question(
    id: 24,
    question_text: "Qual é um exemplo de banco de dados NoSQL baseado em grafos?",
    options: ['MySQL', 'PostgreSQL', 'MongoDB', 'Neo4j'],
    correctAnswer:3,
  ),Question(
    id: 25,
    question_text: "Qual das seguintes opções é verdadeira sobre bancos de dados SQL?",
    options: ['Bancos de dados SQL têm esquema flexível.',
      'Bancos de dados SQL não suportam transações ACID.',
      'Bancos de dados SQL são altamente escaláveis apenas horizontalmente.',
      'Bancos de dados SQL são adequados apenas para consultas simples.'],
    correctAnswer:0,
  ),Question(
    id: 26,
    question_text: "O que significa a sigla ACID em transações de banco de dados?",
    options: ['Atomicidade, Consistência, Isolamento, Durabilidade',
      'Agilidade, Conformidade, Integridade, Durabilidade',
      'Autenticidade, Credibilidade, Integridade, Desempenho',
      'Arquivamento, Compactação, Indexação, Descompressão'],
    correctAnswer:0,
  ),
  Question(
    id: 27,
    question_text: "Qual das seguintes opções é verdadeira sobre bancos de dados NoSQL em relação à escalabilidade?",
    options: ['Bancos de dados NoSQL são escaláveis apenas verticalmente.',
      'Bancos de dados NoSQL são escaláveis apenas horizontalmente.',
      'Bancos de dados NoSQL são escaláveis tanto vertical quanto horizontalmente.',
      'Bancos de dados NoSQL não são escaláveis.'],
    correctAnswer:2,
  ),
  Question(
    id: 28,
    question_text: "O que é consistência eventual em bancos de dados NoSQL?",
    options: ['Garante que todos os nós de um cluster de banco de dados estejam atualizados em tempo real.',
      'Permite que os dados sejam consistentes após um período de tempo, sem garantir imediatamente após a gravação.',
      'Mantém os dados consistentes em diferentes bancos de dados NoSQL.',
      'Garante a consistência em transações complexas em bancos de dados NoSQL.'],
    correctAnswer:1,
  ),
  Question(
    id: 29,
    question_text: "Quais são as desvantagens de usar um banco de dados NoSQL?",
    options: ['Falta de suporte a consultas complexas e falta de suporte a transações ACID.',
      'Dificuldade de escalabilidade e maior complexidade de desenvolvimento.',
      'Baixa disponibilidade e falta de flexibilidade no esquema de dados.',
      'Menor desempenho em consultas ad-hoc e falta de suporte a consultas SQL.'],
    correctAnswer:0,
  ),
  Question(
    id: 30,
    question_text: "Qual das seguintes opções é um exemplo de banco de dados SQL?",
    options: ["Cassandra", "MongoDB", "PostgreSQL", "Redis"],
    correctAnswer:2,
  ),
];